import os

SUPABASE_URL = "https://vtrdsnvqheiexdheudds.supabase.co" 
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0cmRzbnZxaGVpZXhkaGV1ZGRzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MDYwNDgzMiwiZXhwIjoyMDU2MTgwODMyfQ.0r87m4BEZQ_bi0aCqafCTUG-9Dv4uBxc4_RhHxxJ2T0"  # Reemplaza con tu API Key